name: circular_placeholder
description: Circular Placeholder Widget.
version: 0.0.2
repository: https://github.com/leventkantaroglu/circular_placeholder/
documentation: https://github.com/leventkantaroglu/circular_placeholder/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
